-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 18:29:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HealthSafe
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HealthSafe` ;

-- -----------------------------------------------------
-- Schema HealthSafe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HealthSafe` DEFAULT CHARACTER SET utf8 ;
USE `HealthSafe` ;

-- -----------------------------------------------------
-- Table `HealthSafe`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HealthSafe`.`User` ;

CREATE TABLE IF NOT EXISTS `HealthSafe`.`User` (
  `login` VARCHAR(16) NOT NULL,
  `pass` VARCHAR(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `smoke_frequency_per_week` INT NOT NULL,
  `alcool_frequency_per_week` INT NOT NULL,
  `exercise_frequency_per_week` INT NOT NULL,
  `height` FLOAT NOT NULL,
  `sexo` VARCHAR(30) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `url_foto` VARCHAR(45) NOT NULL,  
  `data_nascimento` DATE NOT NULL,
  `data_cadastro` DATE NOT NULL,

  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthSafe`.`Day_Tip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HealthSafe`.`Day_Tip` ;

CREATE TABLE IF NOT EXISTS `HealthSafe`.`Day_Tip` (
  `idDay_Tip` INT AUTO_INCREMENT,
  `day_tip_title` VARCHAR(45) NOT NULL,
  `day_tip_text` TEXT NOT NULL,
  `url_image` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`idDay_Tip`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthSafe`.`Day_Atualization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HealthSafe`.`Day_Atualization` ;

CREATE TABLE IF NOT EXISTS `HealthSafe`.`Day_Atualization` (
  `idDay_Atualization` INT AUTO_INCREMENT,
  `systolic_pressure` FLOAT NOT NULL,
  `diastolic_pressure` FLOAT NOT NULL,
  `weight` FLOAT NOT NULL,
  `alcool` TINYINT NOT NULL,
  `smoke` TINYINT NOT NULL,
  `exercise` TINYINT NOT NULL,
  `fast_food` TINYINT NOT NULL,
  `User_login` VARCHAR(16) NOT NULL,
  `classification_pressure` VARCHAR(45) NOT NULL,
  `classification_imc` VARCHAR(45) NOT NULL,
  `imc` FLOAT NOT NULL,
  `day_tip` INT NOT NULL,
  `day_atualization` DATE NOT NULL,
  PRIMARY KEY (`idDay_Atualization`),
  INDEX `fk_Day_Atualization_User_idx` (`User_login` ASC) ,
  INDEX `fk_Day_Atualization_Day_Tip1_idx` (`day_tip` ASC) ,
  CONSTRAINT `fk_Day_Atualization_User`
    FOREIGN KEY (`User_login`)
    REFERENCES `HealthSafe`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Day_Atualization_Day_Tip1`
    FOREIGN KEY (`day_tip`)
    REFERENCES `HealthSafe`.`Day_Tip` (`idDay_Tip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthSafe`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HealthSafe`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `HealthSafe`.`Doctor` (
  `CRA` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CRA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HealthSafe`.`User_Doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HealthSafe`.`User_Doc` ;

CREATE TABLE IF NOT EXISTS `HealthSafe`.`User_Doc` (
  `idUser_Doc` INT AUTO_INCREMENT,
  `User_login` VARCHAR(16) NOT NULL,
  `Doctor_CRA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser_Doc`),
  INDEX `fk_User_Doc_User1_idx` (`User_login` ASC) ,
  INDEX `fk_User_Doc_Doctor1_idx` (`Doctor_CRA` ASC) ,
  CONSTRAINT `fk_User_Doc_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `HealthSafe`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Doc_Doctor1`
    FOREIGN KEY (`Doctor_CRA`)
    REFERENCES `HealthSafe`.`Doctor` (`CRA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Day_tip(day_tip_title,day_tip_text,url_image) VALUES
("Exercite-se !","Além de todos os benefícios que a prática de exercícios físicos traz ao corpo, ela ainda ajuda a controlar a pressão arterial e reduzir o peso corporal - outro agente que contribui para a hipertensão. As atividades aeróbicas são as mais indicadas. ","day_tip_images\\dica 1.png"),
("Reduza o consumo de Sal !","Evite produtos em conserva, embutidos, salgadinhos, biscoitos recheados, alimentos processados, refrigerantes, queijos amarelos, temperos prontos e procure não adicionar mais sal ao seu prato, buscando sempre substituir por temperos naturais.","day_tip_images\\dica 2.png"),
("Cuidado com a gordura na cintura !","O acúmulo de gordura na região abdominal tem ligação direta com a hipertensão, infarto e diabetes.Para isso, não tem mistério: é a combinação de uma alimentação saudável com a prática de atividades físicas. ","day_tip_images\\dica 3.png"),
("Reduza a ingestão de álcool!","O consumo de bebidas alcoólicas pode ser danoso a sua saúde, por este motivo, reduza ou elimine o seu consumo.","day_tip_images\\dica 4.png"),
("NÃO FUME !","A nicotina é um dos elementos responsáveis pela pressão alta, além de todos os outros malefícios da substância. Pelo bem da sua saúde, largue o cigarro de vez!","day_tip_images\\dica 5.png"),
("Elimine o estresse !","O estresse excessivo é um dos responsáveis por desencadear diversas doenças, dentre elas a hipertensão. Respeite seus limites, durma bem, descanse, pratique atividades físicas e reserve um tempo para o lazer. ","day_tip_images\\dica 6.png");

